version: '3'
services:
  web:
    image: catweb:latest
    ports:
      - "5001:5000"
    volumes:
      - .:/usr/src/app
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
